### ISSUE TITLE
Pré visualização de serviço durante edição

### ISSUE THREAD

**Issue by jeankirchner** [servicosgovbr/editor-de-servicos#75]

**Comment by sahrosa** [comment]
Vamos incluir um botão para visualização do preview no cabeçalho do editor:

![image](https://cloud.githubusercontent.com/assets/2932644/9008703/7063f064-3772-11e5-9db9-781fdb967df9.png)

O preview será apenas do miolo do conteúdo:

![image](https://cloud.githubusercontent.com/assets/2932644/9008718/8e64372c-3772-11e5-8a03-e9d32fe963aa.png)

**Comment by sahrosa** [comment]
Isso é algo que vai tomar muito tempo @cv @kchnr? Ou podemos priorizar?

**Comment by cv** [comment]
Vai tomar bastante tempo - precisamos da nova página do serviço v3 no portal, e um jeito de passar os dados da carta ainda em edição pro portal. Não dá pra prometer pros próximos dias, infelizmente.

**Comment by sahrosa** [comment]
Ok!

**Comment by cv** [comment]
Depende da https://github.com/servicosgovbr/portal-de-servicos/issues/443

**Comment by oliviagj** [comment]
@cv, podemos fazer disso um "0"? @mformiga levantou isso como bastante urgente.

**Comment by cv** [comment]
Bora! Depende da servicosgovbr/portal-de-servicos#447, podemos jogá-la assim que tivemos a página do serviço revisada.

**Comment by oliviagj** [comment]
@cv quais são os cartões de dependência aqui? preciso acompanhar esse cara

**Comment by cv** [comment]
Só esse, mesmo. A gente tinha pensado em umas arquiteturas mais doidas, onde o Editor pede pro Portal renderizar o preview, mas acho que vai ser melhor compartilhar código entre os dois, mesmo.

Pros:
- Mais fácil de codificar, testar, modificar
- Podemos fazer mais ajustes finos no CSS do editor para encaixar a pré-visualização
- Podemos usar pop-ups ao invés de ter que abrir novas abas para mostrar o preview (sem iframes, etc)

Cons:
- Modificações na página do serviço no portal não vão se refletir automaticamente no editor
- Código duplicado, inicialmente

**Comment by oliviagj** [comment]
que tal fazermos a versão rápida e lançar um cartão de dívida técnica para uma pessoa do futuro?

**Comment by kchnr** [comment]
@oliviagj - a forma mais rápida IMHO é mandar para o portal fazer a pré visualização, a abrir em outra aba mesmo. O @cv havia comentado que pode haver alguns problemas de tentarem carregar o servidor com ataques, mas acho que isso é possível em qualquer página, não? Com o número suficientes de request.

**Comment by cv** [comment]
@kchnr não acho uma boa fazer a pre-visualização acontecer no portal, pelos motivos do https://github.com/servicosgovbr/editor-de-servicos/issues/75#issuecomment-139392046 - o buraco de segurança em potencial é bem grande, depois eu explico com mais detalhes. Por enquanto, vamos deixar a pre-visualizacao 100% no Editor, mesmo.

**Comment by gustavo-freitas** [comment]
Estamos explorando a possibilidade de apresentar a pré visualização na mesma página que o editor. Sem janelas auxiliares. @brunoleite irá atualizar os comentários com mais detalhes.

**Comment by brunoleite** [comment]
As seguintes atividades foram levantas para execução da visualização:

- [x] Estrutura Básica de Navegação
- [x] Visualização de Nome e Sigla
- [x] Componente de Ancoras
- [] Componente de Descrição
- [] Componente de Solicitantes
- [] Componente de Etapas
- [] Componente de Tempo
- [] Componente de Legislação
- [] Componente de Outras Inforamações
- [] Componente de Feedback
- [] Visualizar dados não salvos
- [] Adaptar CSS

**Comment by kchnr** [comment]
@brunoleite - como esses itens são essenciais para completar o cartão, que tal colocar na descrição, ao invés de deixar nos comentários?

Assim, podemos confiar mais na descrição do cartão, e comentários é só para discussão mesmo.

**Comment by sahrosa** [comment]
Melhorias percebidas:

- [ ] não mostrar o campo de feedback do serviço ao final da página
- [ ] não mostrar os botões de imprimir e editar a página
- [ ] a informação "Informações adicionais ao tempo estimado" só deverá ser mostrada quando houver alguma informação preenchida no campo de informações adicionais ao campo. isto ainda deve ser implementado no portal conforme cartão #329 
- [ ] mostrar a informação do contato do serviço. ainda está sendo implementado no cartão #474
- [ ] acontecerão algumas mudanças visuais nos solicitantes, e serão vistas no cartão #477

**Comment by sahrosa** [comment]
@gustavo-freitas percebeu também:
- [ ] Nome do custo está colado no valor

![image](https://cloud.githubusercontent.com/assets/2932644/10494596/8ddda760-728d-11e5-9e9b-88cef76c3995.png)

**Comment by gustavo-freitas** [comment]
De acordo com testes exploratórios com o Fabrício, encontramos os seguintes pontos:
[ ] Visualizar não aparecer para o Orgão
[ ] Links no visualizar estão quebrados (URL não é formada corretamente)
[ ] Links de etapas não estão funcionando

**Comment by kchnr** [comment]
Visualizar, é meramente visual, hoje não há nenhum comportamento, inclusive para links. Sugiro criamos cartões específicos para coisas que queremos a mais, assim podemos priorizar de acordo com o todo.

**Comment by gustavo-freitas** [comment]
Conforme conversa com Fabrício e Sá, não iremos realizar nenhuma mudança no comportamento dos links na visualização.

**Comment by gustavo-freitas** [comment]
Funcionalidade verificada com Mauricio e Fabricio.

**Comment by gustavo-freitas** [comment]
Foi encontrado um bug onde o contato não é exibido na visualização. Verificar presença de  markdown e criar cartão,

**Comment by sahrosa** [comment]
Vou verificar e criar o cartão @gustavo-freitas!

**Comment by sahrosa** [comment]
Cartão #397 criado para resolver o problema da informação do contato do serviço.
